# ----------------------------
# Makefile Options
# ----------------------------

NAME = SNAKE
DESCRIPTION = "Snake for the TI-84 Plus CE"
COMPRESSED = NO
ARCHIVED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
